services:
  db:
    image: postgres:12
    volumes:
      - postgres-db:/var/lib/postgresql/data
    extends:
      file: compose.common.yaml
      service: common
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails-docker
      - gem_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    extends:
      file: compose.common.yaml
      service: common
    tty: true
    stdin_open: true
volumes:
  postgres-db:
  gem_data:
