version: "3.8"

services:
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: development.env
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails-docker
      - gem_data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: development.env
    tty: true
    stdin_open: true
volumes:
  db-data:
  gem_data:
